name: AnomalyHop
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.2
  - scikit-image=0.17.2
  - scikit-learn=0.24.1
  - tqdm=4.59.0
  - pytorch=1.5.1
  - torchvision=0.6.1
  - cudatoolkit=10.1
  - matplotlib=3.3.4